travis:
  secure:
    BINSTAR_TOKEN: Z57XhUzWEU5DNbOte3TTWGobPC9Z80tx9Vx0ZZ90A5PfkX16eFDsEh0ZEfnTF6OSFM7GBVl9cynQIGYI9n8cvirYN4f0E98vya2bvdhn+CxR6cYXwQmsmzfCg1hDpb6cW/+F4O5/0t9bTzokyCq7U57bvHvM1AhrmIgSTxzGM74VMYExywClurZKmIF6ZRwo5vr0KNP9DBlf5UtRrfKFbviHBhlO7KZLzDbcBSoV1aHNZQ824FlBGbUVsF78Z5Rjx/8NrZgXmbrohANIIeQX4G/S+egXlU1L7hAtv9tvY+AFMqlIiA2TEM3VR4J7sxsFLic2Of1SO8IgLFTdud6+xaiQtez3MGTLja803BzFvnEC6xdXmyxspqDqVMO91qe0jMCCoCMQhXlp40Cxw/onUendBvF5YBKbbkhZumTv1H9AJHiZ7QjgYye2Y3iKrHrZnQ4eGJaheNeoDJaYm8qI4y4iA4HxQwNUh/a/VItV1/oH4jYZLT9elxS6xONkJh2vab2+87sz/wJRMsHWvHoBfmlQSYuKuuZ+P6Fy6RPTJrh0GkTud8HI9A3ENCAH1Gm7JcHrzyPMUYDdlBjWS3Tz3n/rpCLdPbURhMpr8IlZEAoNKjpAKgHtGtsYLqfyol6utI0S4fwjT+VZJaHpyO3bVIHOeb2HvH2TnZknjQP+uGs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
